package localization

const (
	MsgUnauthorizedError   = "auth.error.unauthorized"
	MsgBadRequestError     = "error.bad_request"
	MsgInternalServerError = "error.internal_server"
	LblCountryGermany      = "country.Germany"
	LblCountryBelgium      = "country.Belgium"
	LblCountryFrance       = "country.France"
	LblCountryPortugal     = "country.Portugal"
	LblCountrySpain        = "country.Spain"
	LblCountryScotland     = "country.Scotland"
	LblCountryTurkey       = "country.Turkey"
	LblCountryAustria      = "country.Austria"
	LblCountryEngland      = "country.England"
	LblCountryHungary      = "country.Hungary"
	LblCountrySlovakia     = "country.Slovakia"
	LblCountryAlbania      = "country.Albania"
	LblCountryDenmark      = "country.Denmark"
	LblCountryNetherlands  = "country.Netherlands"
	LblCountryRomania      = "country.Romania"
	LblCountrySwitzerland  = "country.Sitzerland"
	LblCountrySerbia       = "country.Serbia"
	LblCountryItaly        = "country.Italy"
	LblCountryCzechia      = "country.Czechia"
	LblCountrySlovenia     = "country.Slovenia"
	LblCountryCroatia      = "country.Croatia"
	LblCountryGeorgia      = "country.Georgia"
	LblCountryUkraine      = "country.Ukraine"
	LblCountryPoland       = "country.Poland"
	LblPositionGoalkeeper  = "player.label.position.goalkeeper"
	LblPositionDefender    = "player.label.position.defender"
	LblPositionMidfielder  = "player.label.position.midfielder"
	LblPositionAttacker    = "player.label.position.attacker"
)
